---
title: "README"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


##DATA DICTIONARY – SAMSUNG DATA - AVERAGE (PEER-GRADED ASSIGNMENT)

The final data set is a table of 180 columns and 561 rows.

Columns are recognized by 2 values concatenated by ‘.’. First value refers to the ID of the subject and latter part refers to the activity the measurement belongs to. 

    Ex: X1.LAYING refers to the measurements of X1 while Laying.
    
Since there are 30 subjects and 6 activities (	LAYING
						                        SITTING 
                                                STANDING
                                                WALKING
                                                WALKING DOWNSTAIRS
                                                WALKING UPSTAIRS	) there are 180 (6 x 30) columns.

List of columns: 

1.	"X1.LAYING"
2.	"X2.LAYING"
3.	"X3.LAYING"
4.	"X4.LAYING"
5.	"X5.LAYING"
6.	"X6.LAYING"
7.	"X7.LAYING"
8.	"X8.LAYING"
9.	"X9.LAYING"
10.	"X10.LAYING"
11.	"X11.LAYING"
12.	"X12.LAYING"
13.	"X13.LAYING"
14.	"X14.LAYING"
15.	"X15.LAYING"
16.	"X16.LAYING"
17.	"X17.LAYING"
18.	"X18.LAYING"
19.	"X19.LAYING"
20.	"X20.LAYING"
21.	"X21.LAYING"
22.	"X22.LAYING"
23.	"X23.LAYING"
24.	"X24.LAYING"
25.	"X25.LAYING"
26.	"X26.LAYING"
27.	"X27.LAYING"
28.	"X28.LAYING"
29.	"X29.LAYING"
30.	"X30.LAYING"

31.	"X1.SITTING"
32.	"X2.SITTING"
33.	"X3.SITTING"
34.	"X4.SITTING"
35.	"X5.SITTING"
36.	"X6.SITTING"
37.	"X7.SITTING"
38.	"X8.SITTING"
39.	"X9.SITTING"
40.	"X10.SITTING"
41.	"X11.SITTING"
42.	"X12.SITTING"
43.	"X13.SITTING"
44.	"X14.SITTING"
45.	"X15.SITTING"
46.	"X16.SITTING"
47.	"X17.SITTING"
48.	"X18.SITTING"
49.	"X19.SITTING"
50.	"X20.SITTING"
51.	"X21.SITTING"
52.	"X22.SITTING"
53.	"X23.SITTING"
54.	"X24.SITTING"
55.	"X25.SITTING"
56.	"X26.SITTING"
57.	"X27.SITTING"
58.	"X28.SITTING"
59.	"X29.SITTING"
60.	"X30.SITTING"

61.	"X1.STANDING"
62.	"X2.STANDING"
63.	"X3.STANDING"
64.	"X4.STANDING"
65.	"X5.STANDING"
66.	"X6.STANDING"
67.	"X7.STANDING"
68.	"X8.STANDING"
69.	"X9.STANDING"
70.	"X10.STANDING"
71.	"X11.STANDING"
72.	"X12.STANDING"
73.	"X13.STANDING"
74.	"X14.STANDING"
75.	"X15.STANDING"
76.	"X16.STANDING"
77.	"X17.STANDING"
78.	"X18.STANDING"
79.	"X19.STANDING"
80.	"X20.STANDING"
81.	"X21.STANDING"
82.	"X22.STANDING"
83.	"X23.STANDING"
84.	"X24.STANDING"
85.	"X25.STANDING"
86.	"X26.STANDING"
87.	"X27.STANDING"
88.	"X28.STANDING"
89.	"X29.STANDING"
90.	"X30.STANDING"

91.	"X1.WALKING"
92.	"X2.WALKING"
93.	"X3.WALKING"
94.	"X4.WALKING"
95.	"X5.WALKING"
96.	"X6.WALKING"
97.	"X7.WALKING"
98.	"X8.WALKING"
99.	"X9.WALKING"
100.	"X10.WALKING"
101.	"X11.WALKING"
102.	"X12.WALKING"
103.	"X13.WALKING"
104.	"X14.WALKING"
105.	"X15.WALKING"
106.	"X16.WALKING"
107.	"X17.WALKING"
108.	"X18.WALKING"
109.	"X19.WALKING"
110.	"X20.WALKING"
111.	"X21.WALKING"
112.	"X22.WALKING"
113.	"X23.WALKING"
114.	"X24.WALKING"
115.	"X25.WALKING"
116.	"X26.WALKING"
117.	"X27.WALKING"
118.	"X28.WALKING"
119.	"X29.WALKING"
120.	"X30.WALKING"

121.	"X1.WALKING_DOWNSTAIRS"
122.	"X2.WALKING_DOWNSTAIRS"
123.	"X3.WALKING_DOWNSTAIRS"
124.	"X4.WALKING_DOWNSTAIRS"
125.	"X5.WALKING_DOWNSTAIRS"
126.	"X6.WALKING_DOWNSTAIRS"
127.	"X7.WALKING_DOWNSTAIRS"
128.	"X8.WALKING_DOWNSTAIRS"
129.	"X9.WALKING_DOWNSTAIRS"
130.	"X10.WALKING_DOWNSTAIRS"
131.	"X11.WALKING_DOWNSTAIRS"
132.	"X12.WALKING_DOWNSTAIRS"
133.	"X13.WALKING_DOWNSTAIRS"
134.	"X14.WALKING_DOWNSTAIRS"
135.	"X15.WALKING_DOWNSTAIRS"
136.	"X16.WALKING_DOWNSTAIRS"
137.	"X17.WALKING_DOWNSTAIRS"
138.	"X18.WALKING_DOWNSTAIRS"
139.	"X19.WALKING_DOWNSTAIRS"
140.	"X20.WALKING_DOWNSTAIRS"
141.	"X21.WALKING_DOWNSTAIRS"
142.	"X22.WALKING_DOWNSTAIRS"
143.	"X23.WALKING_DOWNSTAIRS"
144.	"X24.WALKING_DOWNSTAIRS"
145.	"X25.WALKING_DOWNSTAIRS"
146.	"X26.WALKING_DOWNSTAIRS"
147.	"X27.WALKING_DOWNSTAIRS"
148.	"X28.WALKING_DOWNSTAIRS"
149.	"X29.WALKING_DOWNSTAIRS"
150.	"X30.WALKING_DOWNSTAIRS"

151.	"X1.WALKING_UPSTAIRS"
152.	"X2.WALKING_UPSTAIRS"
153.	"X3.WALKING_UPSTAIRS"
154.	"X4.WALKING_UPSTAIRS"
155.	"X5.WALKING_UPSTAIRS"
156.	"X6.WALKING_UPSTAIRS"
157.	"X7.WALKING_UPSTAIRS"
158.	"X8.WALKING_UPSTAIRS"
159.	"X9.WALKING_UPSTAIRS"
160.	"X10.WALKING_UPSTAIRS"
161.	"X11.WALKING_UPSTAIRS"
162.	"X12.WALKING_UPSTAIRS"
163.	"X13.WALKING_UPSTAIRS"
164.	"X14.WALKING_UPSTAIRS"
165.	"X15.WALKING_UPSTAIRS"
166.	"X16.WALKING_UPSTAIRS"
167.	"X17.WALKING_UPSTAIRS"
168.	"X18.WALKING_UPSTAIRS"
169.	"X19.WALKING_UPSTAIRS"
170.	"X20.WALKING_UPSTAIRS"
171.	"X21.WALKING_UPSTAIRS"
172.	"X22.WALKING_UPSTAIRS"
173.	"X23.WALKING_UPSTAIRS"
174.	"X24.WALKING_UPSTAIRS"
175.	"X25.WALKING_UPSTAIRS"
176.	"X26.WALKING_UPSTAIRS"
177.	"X27.WALKING_UPSTAIRS"
178.	"X28.WALKING_UPSTAIRS"
179.	"X29.WALKING_UPSTAIRS"
180.	"X30.WALKING_UPSTAIRS"


One row is the average of the subject doing the activity as specified in the Column name.
Rows refers to the 561 features measurements were taken of. 
Ex: Row of "tBodyAcc-mean()-X" has average acceleration in x axis of 30 different subjects doing   6 different activities expanded in 180 columns. 

All 561 rows:

1.	tBodyAcc-mean()-X
2.	tBodyAcc-mean()-Y
3.	tBodyAcc-mean()-Z
4.	tBodyAcc-std()-X
5.	tBodyAcc-std()-Y
6.	tBodyAcc-std()-Z
7.	tBodyAcc-mad()-X
8.	tBodyAcc-mad()-Y
9.	tBodyAcc-mad()-Z
10.	tBodyAcc-max()-X
11.	tBodyAcc-max()-Y
12.	tBodyAcc-max()-Z
13.	tBodyAcc-min()-X
14.	tBodyAcc-min()-Y
15.	tBodyAcc-min()-Z
16.	tBodyAcc-sma()
17.	tBodyAcc-energy()-X
18.	tBodyAcc-energy()-Y
19.	tBodyAcc-energy()-Z
20.	tBodyAcc-iqr()-X
21.	tBodyAcc-iqr()-Y
22.	tBodyAcc-iqr()-Z
23.	tBodyAcc-entropy()-X
24.	tBodyAcc-entropy()-Y
25.	tBodyAcc-entropy()-Z
26.	tBodyAcc-arCoeff()-X,
27.	tBodyAcc-arCoeff()-X,
28.	tBodyAcc-arCoeff()-X,
29.	tBodyAcc-arCoeff()-X,
30.	tBodyAcc-arCoeff()-Y,
31.	tBodyAcc-arCoeff()-Y,
32.	tBodyAcc-arCoeff()-Y,
33.	tBodyAcc-arCoeff()-Y,
34.	tBodyAcc-arCoeff()-Z,
35.	tBodyAcc-arCoeff()-Z,
36.	tBodyAcc-arCoeff()-Z,
37.	tBodyAcc-arCoeff()-Z,
38.	tBodyAcc-correlation()-X,Y
39.	tBodyAcc-correlation()-X,Z
40.	tBodyAcc-correlation()-Y,Z
41.	tGravityAcc-mean()-X
42.	tGravityAcc-mean()-Y
43.	tGravityAcc-mean()-Z
44.	tGravityAcc-std()-X
45.	tGravityAcc-std()-Y
46.	tGravityAcc-std()-Z
47.	tGravityAcc-mad()-X
48.	tGravityAcc-mad()-Y
49.	tGravityAcc-mad()-Z
50.	tGravityAcc-max()-X
51.	tGravityAcc-max()-Y
52.	tGravityAcc-max()-Z
53.	tGravityAcc-min()-X
54.	tGravityAcc-min()-Y
55.	tGravityAcc-min()-Z
56.	tGravityAcc-sma()
57.	tGravityAcc-energy()-X
58.	tGravityAcc-energy()-Y
59.	tGravityAcc-energy()-Z
60.	tGravityAcc-iqr()-X
61.	tGravityAcc-iqr()-Y
62.	tGravityAcc-iqr()-Z
63.	tGravityAcc-entropy()-X
64.	tGravityAcc-entropy()-Y
65.	tGravityAcc-entropy()-Z
66.	tGravityAcc-arCoeff()-X,
67.	tGravityAcc-arCoeff()-X,
68.	tGravityAcc-arCoeff()-X,
69.	tGravityAcc-arCoeff()-X,
70.	tGravityAcc-arCoeff()-Y,
71.	tGravityAcc-arCoeff()-Y,
72.	tGravityAcc-arCoeff()-Y,
73.	tGravityAcc-arCoeff()-Y,
74.	tGravityAcc-arCoeff()-Z,
75.	tGravityAcc-arCoeff()-Z,
76.	tGravityAcc-arCoeff()-Z,
77.	tGravityAcc-arCoeff()-Z,
78.	tGravityAcc-correlation()-X,Y
79.	tGravityAcc-correlation()-X,Z
80.	tGravityAcc-correlation()-Y,Z
81.	tBodyAccJerk-mean()-X
82.	tBodyAccJerk-mean()-Y
83.	tBodyAccJerk-mean()-Z
84.	tBodyAccJerk-std()-X
85.	tBodyAccJerk-std()-Y
86.	tBodyAccJerk-std()-Z
87.	tBodyAccJerk-mad()-X
88.	tBodyAccJerk-mad()-Y
89.	tBodyAccJerk-mad()-Z
90.	tBodyAccJerk-max()-X
91.	tBodyAccJerk-max()-Y
92.	tBodyAccJerk-max()-Z
93.	tBodyAccJerk-min()-X
94.	tBodyAccJerk-min()-Y
95.	tBodyAccJerk-min()-Z
96.	tBodyAccJerk-sma()
97.	tBodyAccJerk-energy()-X
98.	tBodyAccJerk-energy()-Y
99.	tBodyAccJerk-energy()-Z
100.	tBodyAccJerk-iqr()-X
101.	tBodyAccJerk-iqr()-Y
102.	tBodyAccJerk-iqr()-Z
103.	tBodyAccJerk-entropy()-X
104.	tBodyAccJerk-entropy()-Y
105.	tBodyAccJerk-entropy()-Z
106.	tBodyAccJerk-arCoeff()-X,
107.	tBodyAccJerk-arCoeff()-X,
108.	tBodyAccJerk-arCoeff()-X,
109.	tBodyAccJerk-arCoeff()-X,
110.	tBodyAccJerk-arCoeff()-Y,
111.	tBodyAccJerk-arCoeff()-Y,
112.	tBodyAccJerk-arCoeff()-Y,
113.	tBodyAccJerk-arCoeff()-Y,
114.	tBodyAccJerk-arCoeff()-Z,
115.	tBodyAccJerk-arCoeff()-Z,
116.	tBodyAccJerk-arCoeff()-Z,
117.	tBodyAccJerk-arCoeff()-Z,
118.	tBodyAccJerk-correlation()-X,Y
119.	tBodyAccJerk-correlation()-X,Z
120.	tBodyAccJerk-correlation()-Y,Z
121.	tBodyGyro-mean()-X
122.	tBodyGyro-mean()-Y
123.	tBodyGyro-mean()-Z
124.	tBodyGyro-std()-X
125.	tBodyGyro-std()-Y
126.	tBodyGyro-std()-Z
127.	tBodyGyro-mad()-X
128.	tBodyGyro-mad()-Y
129.	tBodyGyro-mad()-Z
130.	tBodyGyro-max()-X
131.	tBodyGyro-max()-Y
132.	tBodyGyro-max()-Z
133.	tBodyGyro-min()-X
134.	tBodyGyro-min()-Y
135.	tBodyGyro-min()-Z
136.	tBodyGyro-sma()
137.	tBodyGyro-energy()-X
138.	tBodyGyro-energy()-Y
139.	tBodyGyro-energy()-Z
140.	tBodyGyro-iqr()-X
141.	tBodyGyro-iqr()-Y
142.	tBodyGyro-iqr()-Z
143.	tBodyGyro-entropy()-X
144.	tBodyGyro-entropy()-Y
145.	tBodyGyro-entropy()-Z
146.	tBodyGyro-arCoeff()-X,
147.	tBodyGyro-arCoeff()-X,
148.	tBodyGyro-arCoeff()-X,
149.	tBodyGyro-arCoeff()-X,
150.	tBodyGyro-arCoeff()-Y,
151.	tBodyGyro-arCoeff()-Y,
152.	tBodyGyro-arCoeff()-Y,
153.	tBodyGyro-arCoeff()-Y,
154.	tBodyGyro-arCoeff()-Z,
155.	tBodyGyro-arCoeff()-Z,
156.	tBodyGyro-arCoeff()-Z,
157.	tBodyGyro-arCoeff()-Z,
158.	tBodyGyro-correlation()-X,Y
159.	tBodyGyro-correlation()-X,Z
160.	tBodyGyro-correlation()-Y,Z
161.	tBodyGyroJerk-mean()-X
162.	tBodyGyroJerk-mean()-Y
163.	tBodyGyroJerk-mean()-Z
164.	tBodyGyroJerk-std()-X
165.	tBodyGyroJerk-std()-Y
166.	tBodyGyroJerk-std()-Z
167.	tBodyGyroJerk-mad()-X
168.	tBodyGyroJerk-mad()-Y
169.	tBodyGyroJerk-mad()-Z
170.	tBodyGyroJerk-max()-X
171.	tBodyGyroJerk-max()-Y
172.	tBodyGyroJerk-max()-Z
173.	tBodyGyroJerk-min()-X
174.	tBodyGyroJerk-min()-Y
175.	tBodyGyroJerk-min()-Z
176.	tBodyGyroJerk-sma()
177.	tBodyGyroJerk-energy()-X
178.	tBodyGyroJerk-energy()-Y
179.	tBodyGyroJerk-energy()-Z
180.	tBodyGyroJerk-iqr()-X
181.	tBodyGyroJerk-iqr()-Y
182.	tBodyGyroJerk-iqr()-Z
183.	tBodyGyroJerk-entropy()-X
184.	tBodyGyroJerk-entropy()-Y
185.	tBodyGyroJerk-entropy()-Z
186.	tBodyGyroJerk-arCoeff()-X,
187.	tBodyGyroJerk-arCoeff()-X,
188.	tBodyGyroJerk-arCoeff()-X,
189.	tBodyGyroJerk-arCoeff()-X,
190.	tBodyGyroJerk-arCoeff()-Y,
191.	tBodyGyroJerk-arCoeff()-Y,
192.	tBodyGyroJerk-arCoeff()-Y,
193.	tBodyGyroJerk-arCoeff()-Y,
194.	tBodyGyroJerk-arCoeff()-Z,
195.	tBodyGyroJerk-arCoeff()-Z,
196.	tBodyGyroJerk-arCoeff()-Z,
197.	tBodyGyroJerk-arCoeff()-Z,
198.	tBodyGyroJerk-correlation()-X,Y
199.	tBodyGyroJerk-correlation()-X,Z
200.	tBodyGyroJerk-correlation()-Y,Z
201.	tBodyAccMag-mean()
202.	tBodyAccMag-std()
203.	tBodyAccMag-mad()
204.	tBodyAccMag-max()
205.	tBodyAccMag-min()
206.	tBodyAccMag-sma()
207.	tBodyAccMag-energy()
208.	tBodyAccMag-iqr()
209.	tBodyAccMag-entropy()
210.	tBodyAccMag-arCoeff()
211.	tBodyAccMag-arCoeff()
212.	tBodyAccMag-arCoeff()
213.	tBodyAccMag-arCoeff()
214.	tGravityAccMag-mean()
215.	tGravityAccMag-std()
216.	tGravityAccMag-mad()
217.	tGravityAccMag-max()
218.	tGravityAccMag-min()
219.	tGravityAccMag-sma()
220.	tGravityAccMag-energy()
221.	tGravityAccMag-iqr()
222.	tGravityAccMag-entropy()
223.	tGravityAccMag-arCoeff()
224.	tGravityAccMag-arCoeff()
225.	tGravityAccMag-arCoeff()
226.	tGravityAccMag-arCoeff()
227.	tBodyAccJerkMag-mean()
228.	tBodyAccJerkMag-std()
229.	tBodyAccJerkMag-mad()
230.	tBodyAccJerkMag-max()
231.	tBodyAccJerkMag-min()
232.	tBodyAccJerkMag-sma()
233.	tBodyAccJerkMag-energy()
234.	tBodyAccJerkMag-iqr()
235.	tBodyAccJerkMag-entropy()
236.	tBodyAccJerkMag-arCoeff()
237.	tBodyAccJerkMag-arCoeff()
238.	tBodyAccJerkMag-arCoeff()
239.	tBodyAccJerkMag-arCoeff()
240.	tBodyGyroMag-mean()
241.	tBodyGyroMag-std()
242.	tBodyGyroMag-mad()
243.	tBodyGyroMag-max()
244.	tBodyGyroMag-min()
245.	tBodyGyroMag-sma()
246.	tBodyGyroMag-energy()
247.	tBodyGyroMag-iqr()
248.	tBodyGyroMag-entropy()
249.	tBodyGyroMag-arCoeff()
250.	tBodyGyroMag-arCoeff()
251.	tBodyGyroMag-arCoeff()
252.	tBodyGyroMag-arCoeff()
253.	tBodyGyroJerkMag-mean()
254.	tBodyGyroJerkMag-std()
255.	tBodyGyroJerkMag-mad()
256.	tBodyGyroJerkMag-max()
257.	tBodyGyroJerkMag-min()
258.	tBodyGyroJerkMag-sma()
259.	tBodyGyroJerkMag-energy()
260.	tBodyGyroJerkMag-iqr()
261.	tBodyGyroJerkMag-entropy()
262.	tBodyGyroJerkMag-arCoeff()
263.	tBodyGyroJerkMag-arCoeff()
264.	tBodyGyroJerkMag-arCoeff()
265.	tBodyGyroJerkMag-arCoeff()
266.	fBodyAcc-mean()-X
267.	fBodyAcc-mean()-Y
268.	fBodyAcc-mean()-Z
269.	fBodyAcc-std()-X
270.	fBodyAcc-std()-Y
271.	fBodyAcc-std()-Z
272.	fBodyAcc-mad()-X
273.	fBodyAcc-mad()-Y
274.	fBodyAcc-mad()-Z
275.	fBodyAcc-max()-X
276.	fBodyAcc-max()-Y
277.	fBodyAcc-max()-Z
278.	fBodyAcc-min()-X
279.	fBodyAcc-min()-Y
280.	fBodyAcc-min()-Z
281.	fBodyAcc-sma()
282.	fBodyAcc-energy()-X
283.	fBodyAcc-energy()-Y
284.	fBodyAcc-energy()-Z
285.	fBodyAcc-iqr()-X
286.	fBodyAcc-iqr()-Y
287.	fBodyAcc-iqr()-Z
288.	fBodyAcc-entropy()-X
289.	fBodyAcc-entropy()-Y
290.	fBodyAcc-entropy()-Z
291.	fBodyAcc-maxInds-X
292.	fBodyAcc-maxInds-Y
293.	fBodyAcc-maxInds-Z
294.	fBodyAcc-meanFreq()-X
295.	fBodyAcc-meanFreq()-Y
296.	fBodyAcc-meanFreq()-Z
297.	fBodyAcc-skewness()-X
298.	fBodyAcc-kurtosis()-X
299.	fBodyAcc-skewness()-Y
300.	fBodyAcc-kurtosis()-Y
301.	fBodyAcc-skewness()-Z
302.	fBodyAcc-kurtosis()-Z
303.	fBodyAcc-bandsEnergy()-,
304.	fBodyAcc-bandsEnergy()-,
305.	fBodyAcc-bandsEnergy()-,
306.	fBodyAcc-bandsEnergy()-,
307.	fBodyAcc-bandsEnergy()-,
308.	fBodyAcc-bandsEnergy()-,
309.	fBodyAcc-bandsEnergy()-,
310.	fBodyAcc-bandsEnergy()-,
311.	fBodyAcc-bandsEnergy()-,
312.	fBodyAcc-bandsEnergy()-,
313.	fBodyAcc-bandsEnergy()-,
314.	fBodyAcc-bandsEnergy()-,
315.	fBodyAcc-bandsEnergy()-,
316.	fBodyAcc-bandsEnergy()-,
317.	fBodyAcc-bandsEnergy()-,
318.	fBodyAcc-bandsEnergy()-,
319.	fBodyAcc-bandsEnergy()-,
320.	fBodyAcc-bandsEnergy()-,
321.	fBodyAcc-bandsEnergy()-,
322.	fBodyAcc-bandsEnergy()-,
323.	fBodyAcc-bandsEnergy()-,
324.	fBodyAcc-bandsEnergy()-,
325.	fBodyAcc-bandsEnergy()-,
326.	fBodyAcc-bandsEnergy()-,
327.	fBodyAcc-bandsEnergy()-,
328.	fBodyAcc-bandsEnergy()-,
329.	fBodyAcc-bandsEnergy()-,
330.	fBodyAcc-bandsEnergy()-,
331.	fBodyAcc-bandsEnergy()-,
332.	fBodyAcc-bandsEnergy()-,
333.	fBodyAcc-bandsEnergy()-,
334.	fBodyAcc-bandsEnergy()-,
335.	fBodyAcc-bandsEnergy()-,
336.	fBodyAcc-bandsEnergy()-,
337.	fBodyAcc-bandsEnergy()-,
338.	fBodyAcc-bandsEnergy()-,
339.	fBodyAcc-bandsEnergy()-,
340.	fBodyAcc-bandsEnergy()-,
341.	fBodyAcc-bandsEnergy()-,
342.	fBodyAcc-bandsEnergy()-,
343.	fBodyAcc-bandsEnergy()-,
344.	fBodyAcc-bandsEnergy()-,
345.	fBodyAccJerk-mean()-X
346.	fBodyAccJerk-mean()-Y
347.	fBodyAccJerk-mean()-Z
348.	fBodyAccJerk-std()-X
349.	fBodyAccJerk-std()-Y
350.	fBodyAccJerk-std()-Z
351.	fBodyAccJerk-mad()-X
352.	fBodyAccJerk-mad()-Y
353.	fBodyAccJerk-mad()-Z
354.	fBodyAccJerk-max()-X
355.	fBodyAccJerk-max()-Y
356.	fBodyAccJerk-max()-Z
357.	fBodyAccJerk-min()-X
358.	fBodyAccJerk-min()-Y
359.	fBodyAccJerk-min()-Z
360.	fBodyAccJerk-sma()
361.	fBodyAccJerk-energy()-X
362.	fBodyAccJerk-energy()-Y
363.	fBodyAccJerk-energy()-Z
364.	fBodyAccJerk-iqr()-X
365.	fBodyAccJerk-iqr()-Y
366.	fBodyAccJerk-iqr()-Z
367.	fBodyAccJerk-entropy()-X
368.	fBodyAccJerk-entropy()-Y
369.	fBodyAccJerk-entropy()-Z
370.	fBodyAccJerk-maxInds-X
371.	fBodyAccJerk-maxInds-Y
372.	fBodyAccJerk-maxInds-Z
373.	fBodyAccJerk-meanFreq()-X
374.	fBodyAccJerk-meanFreq()-Y
375.	fBodyAccJerk-meanFreq()-Z
376.	fBodyAccJerk-skewness()-X
377.	fBodyAccJerk-kurtosis()-X
378.	fBodyAccJerk-skewness()-Y
379.	fBodyAccJerk-kurtosis()-Y
380.	fBodyAccJerk-skewness()-Z
381.	fBodyAccJerk-kurtosis()-Z
382.	fBodyAccJerk-bandsEnergy()-,
383.	fBodyAccJerk-bandsEnergy()-,
384.	fBodyAccJerk-bandsEnergy()-,
385.	fBodyAccJerk-bandsEnergy()-,
386.	fBodyAccJerk-bandsEnergy()-,
387.	fBodyAccJerk-bandsEnergy()-,
388.	fBodyAccJerk-bandsEnergy()-,
389.	fBodyAccJerk-bandsEnergy()-,
390.	fBodyAccJerk-bandsEnergy()-,
391.	fBodyAccJerk-bandsEnergy()-,
392.	fBodyAccJerk-bandsEnergy()-,
393.	fBodyAccJerk-bandsEnergy()-,
394.	fBodyAccJerk-bandsEnergy()-,
395.	fBodyAccJerk-bandsEnergy()-,
396.	fBodyAccJerk-bandsEnergy()-,
397.	fBodyAccJerk-bandsEnergy()-,
398.	fBodyAccJerk-bandsEnergy()-,
399.	fBodyAccJerk-bandsEnergy()-,
400.	fBodyAccJerk-bandsEnergy()-,
401.	fBodyAccJerk-bandsEnergy()-,
402.	fBodyAccJerk-bandsEnergy()-,
403.	fBodyAccJerk-bandsEnergy()-,
404.	fBodyAccJerk-bandsEnergy()-,
405.	fBodyAccJerk-bandsEnergy()-,
406.	fBodyAccJerk-bandsEnergy()-,
407.	fBodyAccJerk-bandsEnergy()-,
408.	fBodyAccJerk-bandsEnergy()-,
409.	fBodyAccJerk-bandsEnergy()-,
410.	fBodyAccJerk-bandsEnergy()-,
411.	fBodyAccJerk-bandsEnergy()-,
412.	fBodyAccJerk-bandsEnergy()-,
413.	fBodyAccJerk-bandsEnergy()-,
414.	fBodyAccJerk-bandsEnergy()-,
415.	fBodyAccJerk-bandsEnergy()-,
416.	fBodyAccJerk-bandsEnergy()-,
417.	fBodyAccJerk-bandsEnergy()-,
418.	fBodyAccJerk-bandsEnergy()-,
419.	fBodyAccJerk-bandsEnergy()-,
420.	fBodyAccJerk-bandsEnergy()-,
421.	fBodyAccJerk-bandsEnergy()-,
422.	fBodyAccJerk-bandsEnergy()-,
423.	fBodyAccJerk-bandsEnergy()-,
424.	fBodyGyro-mean()-X
425.	fBodyGyro-mean()-Y
426.	fBodyGyro-mean()-Z
427.	fBodyGyro-std()-X
428.	fBodyGyro-std()-Y
429.	fBodyGyro-std()-Z
430.	fBodyGyro-mad()-X
431.	fBodyGyro-mad()-Y
432.	fBodyGyro-mad()-Z
433.	fBodyGyro-max()-X
434.	fBodyGyro-max()-Y
435.	fBodyGyro-max()-Z
436.	fBodyGyro-min()-X
437.	fBodyGyro-min()-Y
438.	fBodyGyro-min()-Z
439.	fBodyGyro-sma()
440.	fBodyGyro-energy()-X
441.	fBodyGyro-energy()-Y
442.	fBodyGyro-energy()-Z
443.	fBodyGyro-iqr()-X
444.	fBodyGyro-iqr()-Y
445.	fBodyGyro-iqr()-Z
446.	fBodyGyro-entropy()-X
447.	fBodyGyro-entropy()-Y
448.	fBodyGyro-entropy()-Z
449.	fBodyGyro-maxInds-X
450.	fBodyGyro-maxInds-Y
451.	fBodyGyro-maxInds-Z
452.	fBodyGyro-meanFreq()-X
453.	fBodyGyro-meanFreq()-Y
454.	fBodyGyro-meanFreq()-Z
455.	fBodyGyro-skewness()-X
456.	fBodyGyro-kurtosis()-X
457.	fBodyGyro-skewness()-Y
458.	fBodyGyro-kurtosis()-Y
459.	fBodyGyro-skewness()-Z
460.	fBodyGyro-kurtosis()-Z
461.	fBodyGyro-bandsEnergy()-,
462.	fBodyGyro-bandsEnergy()-,
463.	fBodyGyro-bandsEnergy()-,
464.	fBodyGyro-bandsEnergy()-,
465.	fBodyGyro-bandsEnergy()-,
466.	fBodyGyro-bandsEnergy()-,
467.	fBodyGyro-bandsEnergy()-,
468.	fBodyGyro-bandsEnergy()-,
469.	fBodyGyro-bandsEnergy()-,
470.	fBodyGyro-bandsEnergy()-,
471.	fBodyGyro-bandsEnergy()-,
472.	fBodyGyro-bandsEnergy()-,
473.	fBodyGyro-bandsEnergy()-,
474.	fBodyGyro-bandsEnergy()-,
475.	fBodyGyro-bandsEnergy()-,
476.	fBodyGyro-bandsEnergy()-,
477.	fBodyGyro-bandsEnergy()-,
478.	fBodyGyro-bandsEnergy()-,
479.	fBodyGyro-bandsEnergy()-,
480.	fBodyGyro-bandsEnergy()-,
481.	fBodyGyro-bandsEnergy()-,
482.	fBodyGyro-bandsEnergy()-,
483.	fBodyGyro-bandsEnergy()-,
484.	fBodyGyro-bandsEnergy()-,
485.	fBodyGyro-bandsEnergy()-,
486.	fBodyGyro-bandsEnergy()-,
487.	fBodyGyro-bandsEnergy()-,
488.	fBodyGyro-bandsEnergy()-,
489.	fBodyGyro-bandsEnergy()-,
490.	fBodyGyro-bandsEnergy()-,
491.	fBodyGyro-bandsEnergy()-,
492.	fBodyGyro-bandsEnergy()-,
493.	fBodyGyro-bandsEnergy()-,
494.	fBodyGyro-bandsEnergy()-,
495.	fBodyGyro-bandsEnergy()-,
496.	fBodyGyro-bandsEnergy()-,
497.	fBodyGyro-bandsEnergy()-,
498.	fBodyGyro-bandsEnergy()-,
499.	fBodyGyro-bandsEnergy()-,
500.	fBodyGyro-bandsEnergy()-,
501.	fBodyGyro-bandsEnergy()-,
502.	fBodyGyro-bandsEnergy()-,
503.	fBodyAccMag-mean()
504.	fBodyAccMag-std()
505.	fBodyAccMag-mad()
506.	fBodyAccMag-max()
507.	fBodyAccMag-min()
508.	fBodyAccMag-sma()
509.	fBodyAccMag-energy()
510.	fBodyAccMag-iqr()
511.	fBodyAccMag-entropy()
512.	fBodyAccMag-maxInds
513.	fBodyAccMag-meanFreq()
514.	fBodyAccMag-skewness()
515.	fBodyAccMag-kurtosis()
516.	fBodyBodyAccJerkMag-mean()
517.	fBodyBodyAccJerkMag-std()
518.	fBodyBodyAccJerkMag-mad()
519.	fBodyBodyAccJerkMag-max()
520.	fBodyBodyAccJerkMag-min()
521.	fBodyBodyAccJerkMag-sma()
522.	fBodyBodyAccJerkMag-energy()
523.	fBodyBodyAccJerkMag-iqr()
524.	fBodyBodyAccJerkMag-entropy()
525.	fBodyBodyAccJerkMag-maxInds
526.	fBodyBodyAccJerkMag-meanFreq()
527.	fBodyBodyAccJerkMag-skewness()
528.	fBodyBodyAccJerkMag-kurtosis()
529.	fBodyBodyGyroMag-mean()
530.	fBodyBodyGyroMag-std()
531.	fBodyBodyGyroMag-mad()
532.	fBodyBodyGyroMag-max()
533.	fBodyBodyGyroMag-min()
534.	fBodyBodyGyroMag-sma()
535.	fBodyBodyGyroMag-energy()
536.	fBodyBodyGyroMag-iqr()
537.	fBodyBodyGyroMag-entropy()
538.	fBodyBodyGyroMag-maxInds
539.	fBodyBodyGyroMag-meanFreq()
540.	fBodyBodyGyroMag-skewness()
541.	fBodyBodyGyroMag-kurtosis()
542.	fBodyBodyGyroJerkMag-mean()
543.	fBodyBodyGyroJerkMag-std()
544.	fBodyBodyGyroJerkMag-mad()
545.	fBodyBodyGyroJerkMag-max()
546.	fBodyBodyGyroJerkMag-min()
547.	fBodyBodyGyroJerkMag-sma()
548.	fBodyBodyGyroJerkMag-energy()
549.	fBodyBodyGyroJerkMag-iqr()
550.	fBodyBodyGyroJerkMag-entropy()
551.	fBodyBodyGyroJerkMag-maxInds
552.	fBodyBodyGyroJerkMag-meanFreq()
553.	fBodyBodyGyroJerkMag-skewness()
554.	fBodyBodyGyroJerkMag-kurtosis()
555.	angle(tBodyAccMean,gravity)
556.	angle(tBodyAccJerkMean),gravityMean)
557.	angle(tBodyGyroMean,gravityMean)
558.	angle(tBodyGyroJerkMean,gravityMean)
559.	angle(X,gravityMean)
560.	angle(Y,gravityMean)
561.	angle(Z,gravityMean)



Any cell is of type numeric and has both positive and negative value.
